### PR TITLE
feat: add GitHub Workflow and arm64 support

### PR DESCRIPTION
**Pull request by AlexanderBabel**
There are some things that need to be considered when merging this PR:

- Set the secret for `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`
- Support for GHCR should work out of the box
- After the first build the GHCR package can be connected with the repository. This can be done by following this guide: https://docs.github.com/en/packages/learn-github-packages/connecting-a-repository-to-a-package#connecting-a-repository-to-an-organization-owned-package-on-github

### CODE REVIEW

**Comment by josegonzalez** [comment]
Why do we also want GHCR/what limits does that have?

**Comment by AlexanderBabel** [comment]
The main benefit is another option besides Docker Hub. Currently, GHCR has no pulling/pushing limits for public packages.

I can also remove the code regarding GHCR, if that's not beneficial for this project.

**Comment by josegonzalez** [comment]
Lets drop it for now. It's another thing for me to debug, and I'd rather not spend my time on this.

Would you be willing to make this same change on the following repositories?

- https://github.com/dokku/docker-grafana-graphite
- https://github.com/dokku/docker-wait
- https://github.com/dokku/docker-ambassador

**Comment by josegonzalez** [comment]
Nope, they are all just normal `docker build` calls :)

**Comment by josegonzalez** [comment]
Do you use Dokku or are you using this image outside of Dokku?

**Comment by AlexanderBabel** [comment]
I am just using this image. In the past I used dokku, but I migrated my setup to Kubernetes. Images are now built by my GitHub workflows instead of dokku.

**Comment by josegonzalez** [comment]
Would love to pick your brain on your move from Dokku to Kubernetes (if only to understand why our existing offering wasn't up to par).

**Comment by AlexanderBabel** [comment]
Short version: It happened in 2019 so there wasn't support for Kubernetes directly. I just discovered today that there is now an integration. Additionally, my company at the time wanted a setup that can scale better over multiple vms/hosts so Kubernetes was the choice. It removed administrating effort for us, because we no longer needed to administer each vm and could take advantage of FOSS projects like ArgoCD.

**Comment by AlexanderBabel** [comment]
Btw I would recommend to use something like semantic-release for better management of new versions. Currently, it looks like that you or a team mate of yours tags every version by hand.

**Comment by josegonzalez** [comment]
I basically create a github release each time, thats about it. What would the above bring me?

**Comment by AlexanderBabel** [comment]
It would automatically create a release (including artefacts, changelog etc) based on the commits that where made to the master branch.

It is using [semantics versioning](https://semver.org) and [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) for that.

Documentation of this project: https://semantic-release.gitbook.io/semantic-release/
Example project: 
- Project: https://github.com/AlexanderBabel/database-s3-backup
- Main configuration file: https://github.com/AlexanderBabel/database-s3-backup/blob/main/.releaserc.json
- Changelog: https://github.com/AlexanderBabel/database-s3-backup/blob/main/CHANGELOG.md

**Comment by josegonzalez** [comment]
Might be a bit annoying based on how the commit messages work (and how others make commits/titles), but I'll investigate it :)

**Comment by AlexanderBabel** [comment]
It a commit is not in the conventional commit format, it is just ignored by semantic release. For example you could use the format for merge commits and then only one entry will appear in the changelog/release for the pull request (if the creator of the pull request is not using conventional commits).

**Pull request merged**
